### ISSUE TITLE
rosetree usage report

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/containers-misc#2]
hi, i used rosetree recently because i needed a tree with a zipper on top. it was quite useful to me. 

i ended up adding a few things on top, of which a few may be more generally useful and could be considered for inclusion.
- to_seq for Zipper.t . basically copied from RoseTree.to_seq.
  (i needed to iterate over the tree and find the sibling/aunt/mother/cousin of each node)
- root_path. a sequence of Zipper.t: all nodes from the current focused node up to the root.

i also made a sequence of all the leaves of a Zipper.t and a generator of all its children but i'm not sure if those would be widely useful.
- addresses: to access a node at a certain location i made a function `at: int list -> Zipper.t -> Zipper.t option` which descends down the path of numbered children, and the inverse `addr: Zipper t -> int list` which gives the current address. very useful to me. not sure if generally useful.

all of these functions are super naive and might break for large trees - have not checked.

finally, is it essential to have the tag ``Node` for the type `tree`? a bare tuple could save some typing? but maybe the explicit constructor is better to avoid ambiguity?

my feeling is that a zipper can help to manipulate a tree whose tree structure is meaningful of itself (as opposed to a search tree where the tree structure is for efficiency), so it would make sense to add extra bells and whistles for tree navigation?

n.

**Comment by c-cube** [comment]
Thanks for the feedback! If you want to add code, then you should open a pull request with the changes. They look useful enough, and I will take a look at the implementation. Indeed, navigation in this kind of tree is useful.

The ``Node` constructor is necessary, because OCaml doesn't accept `type 'a t = 'a * 'a t list` (try it out).
